name: Automated Release Creation

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Automated Changelog Update"]
    types:
      - completed

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current version from Cargo.toml
        id: get_version
        run: |
          CURRENT_VERSION=$(yq -r '.package.version' Cargo.toml)
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Generate release notes
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -v --sort newest --latest --github-token ${{ secrets.GITHUB_TOKEN }} --tag ${{ env.CURRENT_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: CHANGELOG.md

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.CURRENT_VERSION }}"
          body: ${{ steps.git-cliff.outputs.content }}
          draft: false
          prerelease: false
